### ISSUE TITLE
Getting error while converting certain .mp4 files

### ISSUE THREAD

**Issue by edthepurple** [Edisoni/webm_bot#1]
First of all, amazing project. thank you.

I wanted it to basically leech videos from websites and send it to telegram.
I changed the code so it sends the final message as Video with my desired options, there's just one problem.

now sometimes (it depends on the website) that I give it a mp4 link, it fails and shows this error:

**[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1932420] Format mov,mp4,m4a,3gp,3g2,mj2 detected only with low score of 1, misdetection possible!
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1932420] moov atom not found
data/720P_1500K_210306701.mp4: Invalid data found when processing input**

how can I solve this?

**Comment by edmand46** [comment]
Hello, thanks for feedback, your problem maybe on this link [moov atom not found](https://github.com/Rob--/SnapWrap/issues/10#issuecomment-82432035)
